### PR TITLE
ROC-1014 Add tag as input

### PR DESCRIPTION
**Pull request by stl-leanix**
Screenshot 2021-09-30 at 08 51 28

Allow tag as an input since it is required by our deployment.

### CODE REVIEW

**Comment by dan-leanix** [comment]
@perbernhardt Afaik we said in the past that this warning can be ignored as it does not affect the deployment itself.

But I can understand @stl-leanix to set `tag` as input parameter of the GitHub Action to get rid of the warning.

**Review by perbernhardt — COMMENTED** [review]
This is not really a solution, because there might be services that don't use "tag" as a variable but instead decided to call it "version". Also there might be even more variables that are expected by the templates.
We could check / migrate all existing deployments / services / templates to only use known variables, but I am not sure whether this is worth it.
I would prefer if we just ignore the warning.
Perhaps we can add an explicit comment in the README, so that users do not wonder about the warning...

**Review by perbernhardt — COMMENTED** [review]
I somehow feel that I don't get the issue across. So "tag" is not an optional input. It is completely specific to the actual user whether that input even exists. Again, he could call that "currentTag" or "deployTag" or "version" or "nextVersion"... Would we want to add all of these to the readme/config?
So again, I see the following valid solutions here:
* Accept the warning and perhaps document it, so that users do not wonder
* Introduce a new property called "variables" that is to be interpreted as a string (e.g. "variables: 'tag=foo'". This removes the warning, but we would need to refactor all workflows using this action
* Github Actions eventually allows to define something like "ignoreUnknownInputs: true"
* You could also switch to using ENV variables, giving "INPUT_TAG" instead of the input tag...

**Comment by dan-leanix** [comment]
I vote for accept the warning, as we have done it since we introduced this LeanIX specific GitHub action, and document it.

**Comment by perbernhardt** [comment]
> I vote for accept the warning, as we have done it since we introduced this LeanIX specific GitHub action, and document it.

Me too ;-)

**Pull request closed without merging**
